In [2]:
x = 1
print(x)

1


In [7]:
import math
x = math.sqrt(1 + x)
print(x)

1.6118477541252516


In [15]:
import math
x = 3
lap = 1
while(x != math.sqrt(x+1)):
    x = math.sqrt(x + 1)
    lap += 1
print(x)
print(lap)

1.618033988749895
32


In [19]:
import sympy as sp
from sympy import *
x = Symbol("x")
ketqua = sp.solve(x-sp.sqrt(1+x),x)
ketqua

[1/2 + sqrt(5)/2]

In [16]:
import numpy as np
v1 = np.array([1,2,3]) #tao vector 3 chieu
v2 = np.array([2,1,0])
v3 = v1 + v2
v3

array([3, 3, 3])

In [20]:
import numpy as np
v1 = np.array([1,2,3]) #tao vector 3 chieu
v2 = np.array([2,1,0])
v3 = 3*v1 + 2*v2
v3

array([7, 8, 9])

In [21]:
v4 = np.hstack([v1,v2])
v4

array([1, 2, 3, 2, 1, 0])

In [22]:
np.dot(v1,v2)

4

In [38]:
import sympy as sy
from sympy import *
angles = np.linspace(0, np.pi/2,5)
angles


array([0.        , 0.39269908, 0.78539816, 1.17809725, 1.57079633])

In [40]:
sy.sin(angles[0]) 

0

In [43]:
from sympy import sin as sysin
angles = np.linspace(0, np.pi/2,5)
sinangle = np.zeros(5) # tuong duong sinangle = np.array([0,0,0,0])
len(angles)
for i in range(len(angles)):
    sinangle[i] = sysin(angles[i])
sinangle

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])