In [2]:
x = 1
print(x)

1


In [7]:
import math
x = math.sqrt(1 + x)
print(x)

1.6118477541252516


In [15]:
import math
x = 3
lap = 1
while(x != math.sqrt(x+1)):
    x = math.sqrt(x + 1)
    lap += 1
print(x)
print(lap)

1.618033988749895
32


In [19]:
import sympy as sp
from sympy import *
x = Symbol("x")
ketqua = sp.solve(x-sp.sqrt(1+x),x)
ketqua

[1/2 + sqrt(5)/2]

In [16]:
import numpy as np
v1 = np.array([1,2,3]) #tao vector 3 chieu
v2 = np.array([2,1,0])
v3 = v1 + v2
v3

array([3, 3, 3])

In [20]:
import numpy as np
v1 = np.array([1,2,3]) #tao vector 3 chieu
v2 = np.array([2,1,0])
v3 = 3*v1 + 2*v2
v3

array([7, 8, 9])

In [21]:
v4 = np.hstack([v1,v2])
v4

array([1, 2, 3, 2, 1, 0])

In [22]:
np.dot(v1,v2)

4

In [38]:
import sympy as sy
from sympy import *
angles = np.linspace(0, np.pi/2,5)
angles


array([0.        , 0.39269908, 0.78539816, 1.17809725, 1.57079633])

In [40]:
sy.sin(angles[0]) 

0

In [43]:
from sympy import sin as sysin
angles = np.linspace(0, np.pi/2,5)
sinangle = np.zeros(5) # tuong duong sinangle = np.array([0,0,0,0])
len(angles)
for i in range(len(angles)):
    sinangle[i] = sysin(angles[i])
sinangle

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])

In [1]:
import numpy as np
goc = np.pi/3
A = np.array([[np.cos(goc),-np.sin(goc)], [np.sin(goc),np.cos(goc)]])
V = np.array([1.,0.])
Y = np.dot(A, V)
Y

array([0.5      , 0.8660254])

In [5]:
from numpy import diff
dx = 0.1
y = [1,2,3,4,4,5,6]
dy = diff(y)/dx
dy

array([10., 10., 10.,  0., 10., 10.])

In [4]:
z = np.array([1,2,3,4,4,5,6])
dz = diff(z)/dx
dz

array([10., 10., 10.,  0., 10., 10.])

In [6]:
from numpy import diff
x = [.1,.2,.5,.6,.7,.8,.9]
y = [1,2,3,4,4,5,6]
dydx = diff(y)/diff(x)
print(dydx)

[10.          3.33333333 10.          0.         10.         10.        ]


In [7]:
from sympy.geometry import *
P1 = Point(0, 0)
P2 = Point(3, 4)
P3 = Point(2, -1)
P4 = Point(-1, 5)

In [18]:
S1 = Segment(P1, P2)
S2 = Segment(P3, P4)

In [17]:
Point.is_collinear(P1,P2,P3)
S2.midpoint

Point2D(1/2, 2)

In [13]:
S1.length

5

In [14]:
S1.slope

4/3

NameError: name 'S2' is not defined